SELECT f.PRODUCT_ID,f.PRODUCT_NAME, SUM(po.AMOUNT * f.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT f 
RIGHT JOIN (
    SELECT p.PRODUCT_ID,p.AMOUNT
    FROM FOOD_ORDER p
    WHERE YEAR(p.PRODUCE_DATE) = '2022' AND MONTH(p.PRODUCE_DATE) = '5'
) AS po ON f.PRODUCT_ID = po.PRODUCT_ID
GROUP BY f.PRODUCT_ID
ORDER BY TOTAL_SALES DESC , f.PRODUCT_ID ASC

# SELECT p.PRODUCT_ID,p.AMOUNT
#     FROM FOOD_ORDER p
#     WHERE YEAR(p.PRODUCE_DATE) = '2022' AND MONTH(p.PRODUCE_DATE) = '5'