WITH RECURSIVE HOURS AS (
    SELECT 0 AS hour
    UNION ALL
    SELECT hour + 1
    FROM Hours
    WHERE hour < 23
)

SELECT h.hour AS "HOUR", COUNT(HOUR(a.DATETIME)) as "COUNT"
FROM ANIMAL_OUTS a RIGHT JOIN HOURS h ON h.hour = HOUR(a.DATETIME)
GROUP BY h.hour
ORDER BY h.hour ASC;

# SELECT DISTINCT (h.hour) AS "HOUR"
# FROM ANIMAL_OUTS a RIGHT JOIN HOURS h ON h.hour = HOUR(a.DATETIME)
# GROUP BY h.hour
