SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_INFO II JOIN (SELECT IT.ITEM_ID
FROM ITEM_INFO II, ITEM_TREE IT
WHERE II.RARITY = "RARE" AND II.ITEM_ID = IT.PARENT_ITEM_ID) AS A
ON II.ITEM_ID = A.ITEM_ID
ORDER BY II.ITEM_ID DESC;

# 희귀도가 RARE인 아이템들의 모든 다음 업그레이드 아이템 출력
# IT 부모아이템 ID랑 II_ITEM_ID가 같으면 이건 II의 부모
