SELECT E2.ID, E2.GENOTYPE, E1.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA E1 JOIN
ECOLI_DATA E2
WHERE E2.PARENT_ID = E1.ID AND (E2.GENOTYPE & E1.GENOTYPE) = E1.GENOTYPE
ORDER BY E2.ID ASC;

# 나의 PARENT_ID 랑 ID가 같은 컬럼의 GENOTYPE을 내가 가지고 있는 ROW 찾기